index:
   path: /
   controller: App\Controller\DefaultController::index
create:
   path: /create
   controller: App\Controller\ClientesController::create
createUser:
    path: /createUser
    controller: App\Controller\UsuariosController::createUser
viewClients:
    path: /viewClients
    controller: App\Controller\ClientesController::viewClients
viewUser:
    path: /viewUser
    controller: App\Controller\UsuariosController::viewUser
login:
    path: /login
    controller: App\Controller\LoginController::login
logout:
    path: /logout
    controller: App\Controller\LogoutController::logout
profile:
    path: /profile
    controller: App\Controller\ProfileController::profile
register:
    path: /register
    controller: App\Controller\RegistrationController::register
view:
    path: /view
    controller: App\Controller\ClientesController::view